### ISSUE TITLE
UDP payload issue

### ISSUE THREAD

**Issue by kbaegis** [cometfish/hubitat_driver_ps4#1]
Just tested; this doesn't do anything, nor does the driver as-is:
`nc -u <ps4 IP> 987 <<<'WAKEUP * HTTP/1.1\nclient-type:a\nauth-type:C\nuser-credential:<removed>\ndevice-discovery-protocol-version:00020020\n\n'`

**Comment by cometfish** [comment]
Did you do the initial linking exactly as described in the readme?
The Wakeup function requires the linking, and it requires the same source MAC address everytime - you can't just send that packet from any machine.

**Comment by kbaegis** [comment]
Absolutely. I did it from my (apple mac) with ps4-waker via npm, and I know the mac was correct as validated by my lease from my dhcp server. 

Going to check wireshark next.

**Comment by cometfish** [comment]
Ok. Does ps4 waker work?

Also check "Enable Turning On PS4 from Network" setting in the PS4's Power Management settings.

**Comment by kbaegis** [comment]
Settings > Power Save Settings > Set Features Available in Rest Mode > Stay Connected to the Internet was disabled. No wonder :D


Retesting

**Comment by kbaegis** [comment]
It works now. Let's see if I can implement poweroff/standby
